"""CLI: live | paper | backtest | validate | optimize | report | status | serve."""
from __future__ import annotations

import argparse
import logging
import sys


def _settings():
    from orb_engine.config.settings import load_settings, validate_settings
    from orb_engine.logging_config import setup_logging
    s = load_settings()
    setup_logging(s.log_level)
    errs = validate_settings(s)
    if errs:
        print("CONFIG ERRORS:", file=sys.stderr)
        for e in errs:
            print(f" - {e}", file=sys.stderr)
        sys.exit(2)
    return s


def cmd_paper(_a):
    s = _settings()
    from orb_engine.broker.paper import PaperBroker
    from orb_engine.core.types import SymbolInfo
    from orb_engine.execution.engine import ORBEngine
    infos = {sym: SymbolInfo(sym, 2, 0.01, 0.01, 1.0, 100, 0.01, 100, 0.01) for sym in s.symbols}
    eng = ORBEngine(s, PaperBroker(10000.0, infos))
    eng.startup_recovery()
    print(eng.status())


def cmd_live(_a):
    s = _settings()
    if s.dry_run:
        print("DRY_RUN=true — no real orders will be sent.")
    from orb_engine.broker.mt5_broker import MT5Broker
    from orb_engine.execution.engine import ORBEngine
    b = MT5Broker(s.mt5_login, s.mt5_password, s.mt5_server, s.mt5_path, s.magic, s.deviation_points)
    eng = ORBEngine(s, b)
    eng.startup_recovery()
    print(eng.status())
    if not s.dry_run:
        eng.run_live_poll()


def cmd_backtest(a):
    s = _settings()
    import glob

    import pandas as pd

    from orb_engine.analytics.plots import plot_equity, plot_r_dist
    from orb_engine.backtest.engine import BacktestEngine
    from orb_engine.backtest.metrics import summarize
    from orb_engine.reporting.report import build_report
    files = sorted(glob.glob(a.data_glob))
    if not files:
        print(f"no files match {a.data_glob}")
        sys.exit(1)
    data = {}
    # map file per symbol: filenames must contain the symbol (case-insensitive).
    # Symbols without a matching file are skipped with a warning — never silently
    # fed another symbol's data. Single-file demo: name it after the symbol.
    for sym in s.symbols:
        match = [f for f in files if sym.lower() in f.lower()]
        if not match:
            print(f"warning: no data file for {sym}; skipping (expected '*{sym}*.csv')")
            continue
        f = match[0]
        df = pd.read_csv(f, parse_dates=True, index_col=0)
        df.index = pd.to_datetime(df.index, utc=True).tz_convert(s.timezone)
        df.columns = [c.lower() for c in df.columns]
        data[sym] = df
    if not data:
        print("no symbol had a matching data file; nothing to backtest")
        sys.exit(1)
    eng = BacktestEngine(s)
    res = eng.run(data)
    summ = summarize(res.trades, res.equity)
    print(f"trades={summ.get('total_trades')} net_R={summ.get('net_R')} win_rate={summ.get('win_rate')}")
    import os
    os.makedirs("reports", exist_ok=True)
    if not res.equity.empty:
        plot_equity(res.equity, "reports/equity.png")
        plot_r_dist(res.trades, "reports/r_dist.png")
    build_report(s.public_dict(), summ,
                 {"files": files, "config_hash": res.config_hash,
                  "slip": s.backtest_slippage_points, "spread": s.backtest_spread_points,
                  "commission": s.backtest_commission, "intrabar": s.intrabar_policy},
                 "reports/report.md")
    print("wrote reports/report.md")


def cmd_validate(_a):
    import subprocess
    r = subprocess.run([sys.executable, "-m", "pytest", "tests/unit", "-q"], check=False)
    sys.exit(r.returncode)


def cmd_optimize(a):
    from orb_engine.backtest.optimizer import evaluate_grid, grid
    cands = grid({"risk_reward": [1.0, 1.5, 2.0, 3.0], "buffer": [0.0, 5.0, 10.0]})
    print(f"{len(cands)} candidates (demo scoring; wire score_fn to backtest for real runs)")
    rows = evaluate_grid(cands, lambda p: {"train": 1.0 / p["risk_reward"], "valid": 0.5 / p["risk_reward"]})
    for r in rows[:5]:
        print(r)


def cmd_report(_a):
    print("reports/report.md generated by `backtest` command (see reports/).")


def _paper_engine(s):
    from orb_engine.broker.paper import PaperBroker
    from orb_engine.core.types import SymbolInfo
    from orb_engine.execution.engine import ORBEngine
    infos = {sym: SymbolInfo(sym, 2, 0.01, 0.01, 1.0, 100, 0.01, 100, 0.01) for sym in s.symbols}
    return ORBEngine(s, PaperBroker(10000.0, infos))


def cmd_status(_a):
    from orb_engine.reporting.status import snapshot_json
    print(snapshot_json(_paper_engine(_settings())))


def cmd_serve(a):
    import threading
    import time

    from orb_engine.reporting.status import serve
    eng = _paper_engine(_settings())
    if a.poll_secs > 0:
        def loop():
            while True:
                try:
                    eng.poll_once()
                except Exception:
                    logging.getLogger("orb_engine").exception("serve poll failed")
                time.sleep(a.poll_secs)
        threading.Thread(target=loop, daemon=True).start()
    print(f"serving status on http://{a.host}:{a.port}/ (Ctrl-C to stop)")
    serve(eng, a.host, a.port)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="orb-engine")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("paper").set_defaults(fn=cmd_paper)
    sub.add_parser("live").set_defaults(fn=cmd_live)
    sub.add_parser("validate").set_defaults(fn=cmd_validate)
    sub.add_parser("optimize").set_defaults(fn=cmd_optimize)
    sub.add_parser("report").set_defaults(fn=cmd_report)
    b = sub.add_parser("backtest")
    b.add_argument("--data-glob", default="data/*.csv")
    b.set_defaults(fn=cmd_backtest)
    sub.add_parser("status").set_defaults(fn=cmd_status)
    sv = sub.add_parser("serve")
    sv.add_argument("--host", default="127.0.0.1")
    sv.add_argument("--port", type=int, default=8765)
    sv.add_argument("--poll-secs", type=int, default=0)
    sv.set_defaults(fn=cmd_serve)
    a = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO)
    a.fn(a)


if __name__ == "__main__":
    main()
